### PR TITLE
bb-node-red-installer: add additional nodes

### PR DESCRIPTION
**Pull request by jadonk**
* node-red-node-beaglebone
* node-red-node-upm
* node-red-node-mongodb

Signed-off-by: Jason Kridner <jdk@ti.com>

### CODE REVIEW

**Comment by RobertCNelson** [comment]
node-red-node-beaglebone has this issue: (need to bump it's i2c depend)

```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)
gyp ERR! System Linux 4.4.8-ti-r23
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/node-red-node-beaglebone/node_modules/octalbonescript/node_modules/i2c
gyp ERR! node -v v0.12.13
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

**Comment by RobertCNelson** [comment]
We need to get:

https://github.com/theoctal/octalbonescript/blob/master/package.json

to bump it's "i2c": to "0.2.1",

**Comment by jadonk** [comment]
@adityapatadia See comment on https://github.com/theoctal/octalbonescript/issues/62

**Comment by jadonk** [comment]
@RobertCNelson worst-case, we can patch it if we are confident this version is only used with newer installs of nodejs. It seems it _probably works_, just breaks installs on node-0.10.

**Comment by RobertCNelson** [comment]
I believe i2c 0.2.1 works with both nodejs v0.10.x & v0.12.x... (bonescript 0.5.0 beta uses i2c 0.2.1) However it's definitely broken for v4.x, most users seem to be migrating to i2cbus which works with v4.x.

**Comment by RobertCNelson** [comment]
Opps, i'm all over the place today:

https://github.com/kelly/node-i2c
```
Node 0.11 and under
npm install i2c@0.1.8
```

**Pull request merged**
