### PR TITLE
binutils-pru: Bump to official 2.38 release

### PR DESCRIPTION
**Pull request by dinuxbg**
Not much changes affecting the PRU backend.

Signed-off-by: Dimitar Dimitrov <dimitar@dinux.eu>

### CODE REVIEW

**Comment by RobertCNelson** [comment]
awesome! @dinuxbg pushing out... btw, we do have a small issue, we need to figure out.. We have issue with teh default bintutils-dev on sharing of some include files... i've got another package we want to package... https://github.com/beagleboard/ti-msp430-gcc  so another version of binutils...

**Comment by dinuxbg** [comment]
This `ctf-api.h` issue should easily be fixed by disabling CTF: https://github.com/dinuxbg/repos/commit/07dc26a3a04239909ed79a4b82b2e7b726377107

I'll try to validate by end of week, and if successful, I'll create a pull request.

**Comment by RobertCNelson** [comment]
@dinuxbg i'm just thinking, could/should we do something like?

https://packages.debian.org/sid/amd64/binutils-avr/filelist

```
/usr/lib/avr/x86_64-linux-gnu/include/ansidecl.h
/usr/lib/avr/x86_64-linux-gnu/include/bfd.h
/usr/lib/avr/x86_64-linux-gnu/include/bfdlink.h
/usr/lib/avr/x86_64-linux-gnu/include/dis-asm.h
/usr/lib/avr/x86_64-linux-gnu/include/plugin-api.h
/usr/lib/avr/x86_64-linux-gnu/include/symcat.h
/usr/lib/avr/x86_64-linux-gnu/lib/libbfd.a
/usr/lib/avr/x86_64-linux-gnu/lib/libbfd.la
/usr/lib/avr/x86_64-linux-gnu/lib/libopcodes.a
/usr/lib/avr/x86_64-linux-gnu/lib/libopcodes.la
```

essentially /usr/lib/avr/

I'm going to need to do something similar with https://github.com/beagleboard/ti-msp430-gcc anyways..

???

**Comment by RobertCNelson** [comment]
Looks like binutils-avr get's a little creative.. ;)

https://salsa.debian.org/debian/binutils-avr/-/blob/master/debian/rules#L77-113

**Comment by dinuxbg** [comment]
`binutuls-pru`  does create `/usr/lib/pru` because it was based on `binutils-avr` package.

I'll pursue removing libctf and simulator, since that seems cleaner fix to me. I also have to remove BFD plugin. All other packaged files have pru-specific paths and file prefixes, so there should be no conflict. I expect it would be the same for msp430.

If you want me to import `binutils-avr` behaviour, it would take me a few weeks to untangle their "little creativeness" :)

**Comment by RobertCNelson** [comment]
Thanks @dinuxbg if it takes more then 30 seconds, don't worry about it. ;)

**Pull request merged**
