### PR TITLE
bone101: update to 1.1.5

### PR DESCRIPTION
**Pull request by jadonk**

### CODE REVIEW

**Comment by RobertCNelson** [comment]
```
User Environment
----------------

APT_CONFIG=/var/lib/sbuild/apt.conf
HOME=/sbuild-nonexistent
LC_ALL=POSIX
LOGNAME=voodoo
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
SCHROOT_ALIAS_NAME=jessie-armhf-sbuild
SCHROOT_CHROOT_NAME=jessie-armhf-sbuild
SCHROOT_COMMAND=env
SCHROOT_GID=1000
SCHROOT_GROUP=voodoo
SCHROOT_SESSION_ID=jessie-armhf-sbuild-3e0aa87d-9710-4558-96be-f89b0c4a42b1
SCHROOT_UID=1000
SCHROOT_USER=voodoo
SHELL=/bin/sh
TERM=xterm
USER=voodoo

dpkg-buildpackage
-----------------

dpkg-buildpackage: source package bone101
dpkg-buildpackage: source version 1.1.5-0rcnee1~bpo80+20160626+1
dpkg-buildpackage: source distribution jessie
dpkg-buildpackage: source changed by Jason Kridner <jdk@ti.com>
 dpkg-source --before-build bone101-1.1.5
dpkg-buildpackage: host architecture armhf
 fakeroot debian/rules clean
dh clean
   dh_testdir
   dh_auto_clean
make[1]: Entering directory '/<<PKGBUILDDIR>>'
rm -rf ./bone101
rm -rf ./node_modules
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
   dh_clean
 dpkg-source -b bone101-1.1.5
dpkg-source: info: using source format `3.0 (quilt)'
dpkg-source: info: building bone101 using existing ./bone101_1.1.5.orig.tar.gz
dpkg-source: info: building bone101 in bone101_1.1.5-0rcnee1~bpo80+20160626+1.debian.tar.xz
dpkg-source: info: building bone101 in bone101_1.1.5-0rcnee1~bpo80+20160626+1.dsc
 debian/rules build
dh build
   dh_testdir
   dh_auto_configure
   dh_auto_build
make[1]: Entering directory '/<<PKGBUILDDIR>>'
/usr/bin/jekyll build -d ./bone101
Notice: for 10x faster LSI support, please install http://rb-gsl.rubyforge.org/
Configuration file: /<<PKGBUILDDIR>>/_config.yml
            Source: /<<PKGBUILDDIR>>
       Destination: ./bone101
      Generating... 
                    done.
npm not found
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
   dh_auto_test
make[1]: Entering directory '/<<PKGBUILDDIR>>'
htmlproofer not found
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
 fakeroot debian/rules binary
dh binary
   dh_testroot
   dh_prep
   debian/rules override_dh_auto_install
make[1]: Entering directory '/<<PKGBUILDDIR>>'
dh_auto_install -- PREFIX=/usr
make[2]: Entering directory '/<<PKGBUILDDIR>>'
install -m 0755 -d /<<PKGBUILDDIR>>/debian/bone101/usr/share/bone101
cp -dr --preserve=mode,timestamp ./bone101/* /<<PKGBUILDDIR>>/debian/bone101/usr/share/bone101/
install -m 0755 -d /<<PKGBUILDDIR>>/debian/bone101/var/lib/cloud9
install -m 0755 -d /<<PKGBUILDDIR>>/debian/bone101/var/lib/cloud9/.c9
cp -dr --preserve=mode,timestamp ./.c9/* /<<PKGBUILDDIR>>/debian/bone101/var/lib/cloud9/.c9
install -m 0755 -d /<<PKGBUILDDIR>>/debian/bone101/var/lib/cloud9/examples
cp -dr --preserve=mode,timestamp ./examples/* /<<PKGBUILDDIR>>/debian/bone101/var/lib/cloud9/examples
cp -dr --preserve=mode,timestamp ./LICENSE /<<PKGBUILDDIR>>/debian/bone101/var/lib/cloud9
cp -dr --preserve=mode,timestamp ./README.md /<<PKGBUILDDIR>>/debian/bone101/var/lib/cloud9
install -m 0755 -d /<<PKGBUILDDIR>>/debian/bone101/usr/share/applications
cp --preserve=mode,timestamp bone101.desktop /<<PKGBUILDDIR>>/debian/bone101/usr/share/applications/
install -m 0755 -d /<<PKGBUILDDIR>>/debian/bone101/usr/local/lib/node_modules
cp -dr --preserve=mode,timestamp node_modules/* /<<PKGBUILDDIR>>/debian/bone101/usr/local/lib/node_modules/
cp: cannot stat 'node_modules/*': No such file or directory
Makefile:38: recipe for target 'install' failed
make[2]: *** [install] Error 1
make[2]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_install: make -j1 install DESTDIR=/<<PKGBUILDDIR>>/debian/bone101 AM_UPDATE_INFO_DIR=no PREFIX=/usr returned exit code 2
debian/rules:28: recipe for target 'override_dh_auto_install' failed
make[1]: *** [override_dh_auto_install] Error 2
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
debian/rules:17: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
--------------------------------------------------------------------------------
Build finished at 20160626-2128

Finished
--------

E: Build failure (dpkg-buildpackage died)
```

**Comment by RobertCNelson** [comment]
added nodejs: v0.12.x:

https://github.com/rcn-ee/repos/commit/5da2301d629edd6e9d30fa9c8882858e1793015d

Still:

```
User Environment
----------------

APT_CONFIG=/var/lib/sbuild/apt.conf
HOME=/sbuild-nonexistent
LC_ALL=POSIX
LOGNAME=voodoo
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
SCHROOT_ALIAS_NAME=jessie-armhf-nodejs-v0.12.x-sbuild
SCHROOT_CHROOT_NAME=jessie-armhf-nodejs-v0.12.x-sbuild
SCHROOT_COMMAND=env
SCHROOT_GID=1000
SCHROOT_GROUP=voodoo
SCHROOT_SESSION_ID=jessie-armhf-nodejs-v0.12.x-sbuild-d660079a-1c55-4086-aee8-cd85d8d0d2e4
SCHROOT_UID=1000
SCHROOT_USER=voodoo
SHELL=/bin/sh
TERM=xterm
USER=voodoo

dpkg-buildpackage
-----------------

dpkg-buildpackage: source package bone101
dpkg-buildpackage: source version 1.1.5-0rcnee2~bpo80+20160626+1
dpkg-buildpackage: source distribution jessie
dpkg-buildpackage: source changed by Robert Nelson <robertcnelson@gmail.com>
 dpkg-source --before-build bone101-1.1.5
dpkg-buildpackage: host architecture armhf
 fakeroot debian/rules clean
dh clean
   dh_testdir
   dh_auto_clean
make[1]: Entering directory '/<<PKGBUILDDIR>>'
rm -rf ./bone101
rm -rf ./node_modules
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
   dh_clean
 dpkg-source -b bone101-1.1.5
dpkg-source: info: using source format `3.0 (quilt)'
dpkg-source: info: building bone101 using existing ./bone101_1.1.5.orig.tar.gz
dpkg-source: info: building bone101 in bone101_1.1.5-0rcnee2~bpo80+20160626+1.debian.tar.xz
dpkg-source: info: building bone101 in bone101_1.1.5-0rcnee2~bpo80+20160626+1.dsc
 debian/rules build
dh build
   dh_testdir
   dh_auto_configure
   dh_auto_build
make[1]: Entering directory '/<<PKGBUILDDIR>>'
/usr/bin/jekyll build -d ./bone101
Notice: for 10x faster LSI support, please install http://rb-gsl.rubyforge.org/
Configuration file: /<<PKGBUILDDIR>>/_config.yml
            Source: /<<PKGBUILDDIR>>
       Destination: ./bone101
      Generating... 
                    done.
mkdir -p node_modules
cd node_modules
/usr/bin/npm install async@2.0.0-rc.6
npm ERR! Linux 4.4.13-armv7-lpae-x4
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "async@2.0.0-rc.6"
npm ERR! node v0.12.15
npm ERR! npm  v2.15.1
npm ERR! path /sbuild-nonexistent
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/sbuild-nonexistent'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/sbuild-nonexistent'] errno: -13, code: 'EACCES', path: '/sbuild-nonexistent' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /<<PKGBUILDDIR>>/npm-debug.log
Makefile:12: recipe for target 'bone101' failed
make[1]: *** [bone101] Error 243
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_build: make -j1 returned exit code 2
debian/rules:17: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2
--------------------------------------------------------------------------------
Build finished at 20160626-2140

Finished
--------

E: Build failure (dpkg-buildpackage died)
```

**Comment by RobertCNelson** [comment]
for any npm install xyz, i usually add these options: (adjust the prefix to your install directory)

```
npm_options="--unsafe-perm=true --progress=false --loglevel=error --prefix /usr/local"
```

**Comment by jadonk** [comment]
I think I fixed this in the Makefile now. Should be labeled 1.1.6.

**Pull request merged**
