### PR TITLE
Add seasocks, xenomai debian packages configuration

### PR DESCRIPTION
**Pull request by krvprashanth**
Added debian package configuration of Bela  dependencies to include in https://rcn-ee.com/ apt package manager in order to use while building bela images

- seasocks version 1.4.4
- xenomai version 3.0.12

### CODE REVIEW

**Comment by RobertCNelson** [comment]
What's with all the .debhelper files?

**Comment by krvprashanth** [comment]
oh, i added untracked files

debian/rules file that uses debhelper to automate build process

**Comment by krvprashanth** [comment]
x-special/nautilus-clipboard
copy
file:///home/prashanth/Pictures/Screenshot%20from%202022-07-14%2023-45-36.png

**Comment by RobertCNelson** [comment]
okay, added seasocks... https://github.com/rcn-ee/repos/commits/master/bela-seasocks  please redo 'xenomai' and add the version number... 'xenomai-3.0' etc..xenomai changes the abi on every major release..

**Comment by krvprashanth** [comment]
okay

**Pull request closed without merging**
